/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  docs: [
    {
      type: "doc", 
      id: "overview",
      label: "Overview"
    },

    {
      type: "doc", 
      id: "quickstart",
      label: "Quickstart",
      
    },

    {
      type: "category",
      label: "Installation",
      collapsed: true,
      // collapsible: false,
      items: [
        {
          type: 'doc',
          id: 'installation/sourcecode',
        },
        {
          type: 'doc',
          id: 'installation/docker',
        },
        {
          type: 'doc',
          id: 'installation/docker_compose',
        },
        {
          type: 'category',
          label: 'Model Service Deployment',
          items: [
            {
              type: 'doc',
              id: 'installation/model_service/stand_alone',
            },
            {
              type: 'doc',
              id: 'installation/model_service/cluster',
            },
          ],
        },
        {
          type: 'category',
          label: 'Adanced Usage',
          items: [
            {
              type: 'doc',
              id: 'installation/advanced_usage/vLLM_inference',
            },
            {
              type: 'doc',
              id: 'installation/advanced_usage/OpenAI_SDK_call',
            },
          ],
        },


      ],
      link: {
        type: 'generated-index',
        description: 'DB-GPT provides a wealth of installation and deployment options, supporting source code deployment, Docker deployment, cluster deployment and other modes. At the same time, it can also be deployed and installed based on the AutoDL image.',
        slug: "installation",
      },
    },

    // {
    //   type: "category",
    //   label: "Installation",
    //   collapsed: false,
    //   collapsible: false,
    //   items: [{ type: "autogenerated", dirName: "installation" }],
    //   link: {
    //     type: 'generated-index',
    //     description: 'DB-GPT provides a wealth of installation and deployment options, supporting source code deployment, Docker deployment, cluster deployment and other modes. At the same time, it can also be deployed and installed based on the AutoDL image.',
    //     slug: "installation",
    //   },
    // },


    {
      type: "category",
      label: "Operation Manual",
      collapsed: false,
      collapsible: false,
      items: [{ type: "autogenerated",  dirName: "operation_manual"}],
      link: {
        type: "generated-index",
        description: "DB-GPT Operation Manual",
        slug: "operation_manual",
      }
    },
    
    {
      type: "category",
      label: "Modules",
      collapsed: true,
      items: [
        { type: "category", label: "Service-oriented Multi-model Management", collapsed: true, 
          items: [{type:"autogenerated", dirName: "smmf" }], link: { type: 'doc', id: "modules/smmf/index" }
        },
        
      ],
    },

    {
      type: "category",
      label: "Application",
      collapsed: true,
      items: [
        { type: "category", label: "Application", collapsed: true, 
          items: [{type:"autogenerated", dirName: "application" }], link: { type: 'doc', id: "application/index" }
        },
      ],
    },
    
    {
      type: "doc", 
      id: "changelog",
      label: "ChangeLog"
    },

    {
      type: "category",
      label: "Example",
      collapsed: true,
      collapsible: false,
      items: [{ type: "autogenerated",  dirName: "example"}],
      link: {
        type: "generated-index",
        description: "example",
        slug: "example",
      }
    },
  ]
};


module.exports = sidebars;
