/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  docs: [
    {
      type: "doc", 
      id: "overview",
      label: "Overview"
    },

    {
      type: "category",
      label: "Get started",
      collapsed: false,
      collapsible: false,
      items: [{ type: "autogenerated", dirName: "get_started" }],
      link: {
        type: 'generated-index',
        description: 'Get started with DB-GPT',
        slug: "get_started",
      },
    },

    {
      type: "category",
      label: "Installation",
      collapsed: true,
      collapsible: false,
      items: [{ type: "autogenerated",  dirName: "installation"}],
      link: {
        type: "generated-index",
        description: "DB-GPT installation",
        slug: "installation",
      }
    },

    {
      type: "category",
      label: "Modules",
      collapsed: true,
      items: [
        { type: "category", label: "Service-oriented Multi-model Management", collapsed: true, 
          items: [{type:"autogenerated", dirName: "smmf" }], link: { type: 'doc', id: "modules/smmf/index" }
        },
        
      ],
    },

    {
      type: "category",
      label: "Application",
      collapsed: true,
      items: [
        { type: "category", label: "Application", collapsed: true, 
          items: [{type:"autogenerated", dirName: "application" }], link: { type: 'doc', id: "application/index" }
        },
      ],
    },
    
    {
      type: "doc", 
      id: "changelog",
      label: "ChangeLog"
    },
  ]
};


module.exports = sidebars;
